name: Custom Predicate

on:
  workflow_dispatch:
    inputs:
      private-signing:
        description: "Use private signing"
        type: boolean
        default: true
      predicate-source:
        description: "How to supply the predicate"
        type: choice
        options:
          - file
          - literal
        default: file
      show-summary:
        description: "Show attestation summary"
        type: boolean
        default: true

jobs:
  build:
    name: attest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Debug
        uses: ./.github/actions/debug

      - name: Create subject
        run: |
          echo "$RANDOM-$(date +%s)-$(uuidgen)" > subject.txt

      - name: Create predicate (file)
        id: predicate
        run: |
          cat > predicate.json << 'EOF'
          {
            "result": "PASSED",
            "configuration": {},
            "passedTests": ["unit-tests"]
          }
          EOF

          echo "json=$(cat predicate.json | jq -c .)" >> "$GITHUB_OUTPUT"

      - name: Attest artifact (file)
        if: inputs.predicate-source == 'file'
        id: attest-file
        uses: ./.github/actions/attest
        with:
          subject-path: subject.txt
          predicate-type: "https://in-toto.io/attestation/test-result/v0.1"
          predicate-path: predicate.json
          show-summary: ${{ inputs.show-summary }}
          private-signing: ${{ inputs.private-signing }}

      - name: Check output
        if: inputs.predicate-source == 'file'
        run: |
          echo "attestation-id:  ${{ steps.attest-file.outputs.attestation-id }}"
          echo "attestation-url: ${{ steps.attest-file.outputs.attestation-url }}"
          echo "bundle-path:     ${{ steps.attest-file.outputs.bundle-path }}"

          cat ${RUNNER_TEMP}/created_attestation_paths.txt

      - name: Attest artifact (literal)
        if: inputs.predicate-source == 'literal'
        id: attest-literal
        uses: ./.github/actions/attest
        with:
          subject-path: subject.txt
          predicate-type: "https://in-toto.io/attestation/test-result/v0.1"
          predicate: ${{ steps.predicate.outputs.json }}
          show-summary: ${{ inputs.show-summary }}
          private-signing: ${{ inputs.private-signing }}

      - name: Check output
        if: inputs.predicate-source == 'literal'
        run: |
          echo "attestation-id:  ${{ steps.attest-literal.outputs.attestation-id }}"
          echo "attestation-url: ${{ steps.attest-literal.outputs.attestation-url }}"
          echo "bundle-path:     ${{ steps.attest-literal.outputs.bundle-path }}"

          cat ${RUNNER_TEMP}/created_attestation_paths.txt
